run:
  timeout: 10m

issues:
  exclude-dirs:
    - examples/
  max-issues-per-linter: 100
  max-same-issues: 100

linters:
  enable-all: true
  fast: false
  disable:
    - lll
    - wsl
    - depguard
    - tagliatelle
    - gomnd # This linter is deprecated
    - execinquery # This linter is deprecated
    - exportloopref # This linter is deprecated
    - gochecknoglobals
    - ireturn
    - exhaustruct
    - wrapcheck
    - musttag
    - revive
    - varnamelen
    - nonamedreturns
    - gosec
    - funlen
    - interfacebloat
    - dupl
    - err113
    - noctx
    - cyclop
    - tagalign
    - recvcheck

linters-settings:
  gocritic:
    enable-all: true
    disabled-checks:
      - hugeParam
